apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_IMAGE_NAME}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${APP_IMAGE_NAME}-discoverer
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${APP_IMAGE_NAME}-discoverer
subjects:
  - kind: ServiceAccount
    name: ${APP_IMAGE_NAME}
roleRef:
  kind: Role
  name: ${APP_IMAGE_NAME}-discoverer
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  labels:
    app: ${APP_IMAGE_NAME}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${APP_IMAGE_NAME}
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
        version: v1
      annotations:
        container.apparmor.security.beta.kubernetes.io/${APP_IMAGE_NAME}: runtime/default
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/prometheus'
        prometheus.io/port: "8080"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: alpha-app-${ENV}
    spec:
      serviceAccountName: ${APP_IMAGE_NAME}
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 12345
            runAsGroup: 23456
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - all
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              httpHeaders:
                - name: X-B3-Sampled
                  value: "0"
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              httpHeaders:
                - name: X-B3-Sampled
                  value: "0"
            initialDelaySeconds: 2
            periodSeconds: 1
            failureThreshold: 60
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: alpha-common-config
            - configMapRef:
                name: ahb-dtp-test-framework-env
