create database audits;
create database banks;
create database cards;
create database cases;
create database certificates;
create database creditcards;
create database customers;
create database canary;
create database flowable;
create database loans;
create database openbanking;
create database passkit;
create database payments;
create database temenos;
create database banking_config;

grant all privileges on database audits to alpha;
grant all privileges on database banks to alpha;
grant all privileges on database cards to alpha;
grant all privileges on database cases to alpha;
grant all privileges on database certificates to alpha;
grant all privileges on database creditcards to alpha;
grant all privileges on database customers to alpha;
grant all privileges on database canary to alpha;
grant all privileges on database flowable to alpha;
grant all privileges on database loans to alpha;
grant all privileges on database openbanking to alpha;
grant all privileges on database passkit to alpha;
grant all privileges on database payments to alpha;
grant all privileges on database temenos to alpha;
grant all privileges on database banking_config to alpha;
